<table>
    <tr>
        <th colspan=2><h1>Arrays</h1></th>
    </tr>
    <tr>
        <th><img src="animal.jpeg" width=450></th>
        <th><img src="landscape.jpg" width=450></th>
    </tr>
</table>

***

# BMI (body mass index)

Calculate the bmi and return the value in a list<br>
For each pair of values in the lists provided

Apply a limit to the bmi's values

***

#### Prototypes

```python
def give_bmi(height: list[int | float], weight: list[int | float]) -> list[int | float]:
    #your code goes here

def apply_limit(bmi: list[int | float], limit: int) -> list[bool]:
    #your code goes here
```

***

> References:
> 
> [BMI calculator and formula](https://www.calculator.net/bmi-calculator.html?cage=25&csex=m&cheightfeet=5&cheightinch=10&cpound=160&cheightmeter=165&ckg=65&printit=0&ctype=metric&x=Calculate)


In [1]:
import sys


def is_float(n: int) -> bool:
        """Is float
                Details:
                Return true when the parameter is a valid float
        """
        try:
                float(n)
                return True
        except ValueError:
                return False


def give_bmi(height: list[int | float], weight: list[int | float]) -> list[int | float]:
        """Give Body Mass Index

                Details:
                Return a list with the body mass index for the two provided lists
                The bmi is calculated by the following formula: BMI = kg / m^2

                Errors:
                When the lists contain invalid values
                If the lists are not the same size

                Reference:
                https://www.calculator.net/bmi-calculator.html
        """
        error_msg = "AssertionError: either list contains invalid values"
        assert len([_ for _ in height + weight if not is_float(_)]) == 0, error_msg
        error_msg = "AssertionError: the list are not the same size"
        assert len(weight) == len(height), error_msg
        height = [float(_) for _ in height]
        weight = [float(_) for _ in weight]
        return [_w / (_h**2) for _h, _w in zip(height, weight)]


def apply_limit(bmi: list[int | float], limit: int) -> list[bool]:
        return [True if _ > limit else False for _ in bmi]


heights = [2.71, 1.15]
weights =  [165.3, 38.4]

bmi = give_bmi(heights, weights)
print(bmi, type(bmi))

print(apply_limit(bmi, 26))


[22.507863455018317, 29.0359168241966] <class 'list'>
[False, True]


# Array2D

Write a function which takes a 2D array and truncates is accrding to the start and end parameters

The prototype is the following:

```python
def slice_me(family: list, start: int, end: int) -> list:
    #your code here
```


The output expected:

```bash
$> python test_array2D.py
My shape is : (4, 2)
My new shape is : (2, 2)
[[1.8, 78.4], [2.15, 102.7]]
My shape is : (4, 2)
My new shape is : (1, 2)
[[2.15, 102.7]]
```

In [2]:
def slice_me(family: list, start: int, end: int) -> list:
    """slice_me

    Details:
    Slice an array at the start and end and return it.
    Print the original size. Print the new size."""
    col_size = len(family[0])
    rect_martix = len([_ for _ in family if len(_) != col_size]) == 0
    if not rect_martix:
        print("Warning, your matrix is not rectangular, columns vary")
    print(f"My shape is : ({len(family)}, {len(family[0])})")
    new_arr = family[start:end]
    print(f"My new shape is : ({len(new_arr)}, {len(new_arr[0])})")
    return new_arr


family = [[1.80, 78.4],
[2.15, 102.7],
[2.10, 98.5],
[1.88, 75.2]]
print(slice_me(family, 0, 2))
print(slice_me(family, 1, -2))

My shape is : (4, 2)
My new shape is : (2, 2)
[[1.8, 78.4], [2.15, 102.7]]
My shape is : (4, 2)
My new shape is : (1, 2)
[[2.15, 102.7]]


***

# Load Image

Create a function which takes an image and prints its format and the pixel representation to the terminal

***

#### Prototype

```python
def ft_load(path: str) -> np.ndarray:
    #your code goes here
```

 Read an image, print the shape of it and return an array representing each pixel \[R G B\]

***

#### References:
[Matplotlib imshow](https://matplotlib.org/3.8.3/api/_as_gen/matplotlib.axes.Axes.imshow.html#matplotlib.axes.Axes.imshow)

***

##### Note: Handle errors properly

In [3]:
from PIL import Image
import numpy as np

# https://pillow.readthedocs.io/en/stable/reference/Image.html#open-rotate-and-display-an-image-using-the-default-viewer


def ft_load(path: str) -> np.ndarray:
    """ft_load

    Details:
    Read an image pointed by path
    Print the shape of it and return an array representing each pixel [R G B]"""
    try:
        im = np.array(Image.open(path))
        print(f"The shape of the image is: {im.shape}")
        return im
    except (FileNotFoundError, AttributeError) as msg:
        print(msg)

print(ft_load("./landscape.jpg"))

The shape of the image is: (257, 450, 3)
[[[19 42 83]
  [23 42 84]
  [28 43 84]
  ...
  [69 42 51]
  [68 41 46]
  [68 41 46]]

 [[20 43 84]
  [24 43 85]
  [28 43 84]
  ...
  [71 44 53]
  [71 42 47]
  [71 42 47]]

 [[22 44 85]
  [25 44 84]
  [30 45 86]
  ...
  [74 44 54]
  [72 43 48]
  [72 43 48]]

 ...

 [[ 1  0  5]
  [ 1  0  5]
  [ 1  0  5]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 1  0  5]
  [ 1  0  5]
  [ 1  0  5]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  4]
  [ 0  0  4]
  [ 0  0  4]
  ...
  [ 0  0  0]
  [ 1  1  1]
  [ 1  1  1]]]


***

# Zoom on me!

***

Create a program that should load the image "animal.jpeg", print some information<br>
about it and display it after "zooming".
<br>
- Display the scale on the x and y axis on the image
- Display the pixel values on the scale
<br>
If anything went wrong, the program must not stop abruptly and handle any error
with a clear message.

***

#### Expected output:

```bash
$> python zoom.py
The shape of image is: (768, 1024, 3)
[[[120 111 132]
[139 130 151]
[155 146 167]
...
[120 156 94]
[119 154 90]
[118 153 89]]]
New shape after slicing: (400, 400, 1) or (400, 400)
[[[167]
[180]
[194]
...
[102]
[104]
[103]]]
$>
```


In [4]:
from matplotlib import pyplot as plt
import numpy as np


def zoom(start_horz = 450, end_horz = 850, start_vert = 100, end_vert = 500):
    im = ft_load("./animal.jpeg")
    if start_horz >= end_horz or start_vert >= end_vert:
        print("WoW, careful there, not a valid slice")
        return
    #Slice it
    sliced_im = im[start_vert:end_vert, start_horz:end_horz]
    #Channel Gray
    grayscale_table = np.array([[0.3], [0.19], [0.11]])
    print(f"Grayscale: {[[0.3], [0.19], [0.11]]}")
    gray_array = np.dot(sliced_im, grayscale_table)
    #Print info
    print(f"New shape after slicing: {sliced_im.shape}")
    #Show plot
    plt.imshow(gray_array, cmap="gray")
    plt.show()

zoom()

***

# Rotate Me!

Make a program which must load the image "animal.jpeg", cut a square part from it
and transpose (rotate it). Show the new shape
and the data of the image after the transpose.

In [5]:
from matplotlib import pyplot as plt
import numpy as np


def rotate(start_horz = 450, end_horz = 850, start_vert = 100, end_vert = 500):
    im = ft_load("./animal.jpeg")
    if start_horz >= end_horz or start_vert >= end_vert:
        print("WoW, careful there, not a valid slice")
        return
    #Slice it
    sliced_im = im[start_vert:end_vert, start_horz:end_horz]
    #Channel Gray
    grayscale_table = np.array([[0.3], [0.19], [0.11]])
    print(f"Grayscale: {[[0.3], [0.19], [0.11]]}")
    gray_array = np.dot(sliced_im, grayscale_table)
    #Rotate it
    rotated = [[gray_array[j][i] for j in range(len(gray_array))] for i in range(len(gray_array[0]))]
    #Show plot
    plt.imshow(rotated, cmap="gray")
    plt.show()

rotate()

***

# Pimp my image

***

You need to develop 5 functions capable of applying a variety<br>
of color filters to images while keeping the image shape the same.

***

#### Here’s how they should be prototyped :

```python
def ft_invert(array) -> array:
    #your code here

def ft_red(array) -> array:
    #your code here

def ft_green(array) -> array:
    #your code here

def ft_blue(array) -> array:
#your code here

def ft_grey(array) -> array:
#your code here
```

***

#### Notes

You have some restriction operators for each function:<br>
(you can only use those given, you don’t have to use them all)
- invert: =, +, -, *
- red: =, *
- green: =, -
- blue: =
- grey: =, /

In [6]:
import numpy as np


def ft_invert(array) -> np.ndarray:
    """ft_invert

    Details:
    Invert colors, by getting the oposite side of the color
    """
    return [[(255-r, 255-g, 255-b) for r, g, b in _] for _ in array]


def ft_red(array) -> np.ndarray:
    """ft_red

    Details:
    Only allow the red channel
    """
    return [[(r, 0, 0) for r, g, b in _] for _ in array]


def ft_green(array) -> np.ndarray:
    """ft_green

    Details:
    Only allow the green channel
    """
    return [[(0, g, 0) for r, g, b in _] for _ in array]


def ft_blue(array) -> np.ndarray:
    """ft_blue

    Details:
    Only allow the blue channel
    """
    return [[(0, 0, b) for r, g, b in _] for _ in array]


def ft_grey(array) -> np.ndarray:
    """ft_grey

    Details:
    Combine all the colors to a grayscale
    """
    return [[(r/0.3+g/1.9+b/1.1)*0.255 for r, g, b in _] for _ in array]


In [7]:
from matplotlib import pyplot as plt
from matplotlib.widgets import Button
# https://matplotlib.org/3.8.3/api/_as_gen/matplotlib.axes.Axes.imshow.html#matplotlib.axes.Axes.imshow


class ImageSwitcher:
    def __init__(self, images):
        self.images = images
        self.current_image = 0

        self.fig, self.ax = plt.subplots()
        plt.subplots_adjust(bottom=0.2)
        self.img = self.ax.imshow(self.images[self.current_image], cmap='gray')

        self.ax_prev = plt.axes([0.7, 0.05, 0.1, 0.075])
        self.ax_next = plt.axes([0.81, 0.05, 0.1, 0.075])
        self.btn_prev = Button(self.ax_prev, 'Previous')
        self.btn_next = Button(self.ax_next, 'Next')

        self.btn_prev.on_clicked(self.prev_image)
        self.btn_next.on_clicked(self.next_image)

    def prev_image(self, event):
        self.current_image = (self.current_image - 1) % len(self.images)
        self.img.set_data(self.images[self.current_image])
        self.fig.canvas.draw()

    def next_image(self, event):
        self.current_image = (self.current_image + 1) % len(self.images)
        self.img.set_data(self.images[self.current_image])
        self.fig.canvas.draw()



im = ft_load("landscape.jpg")
images = [im, ft_grey(im), ft_blue(im), ft_green(im), ft_red(im), ft_invert(im)]
ImageSwitcher(images)
plt.show()
